package = "arca"
version = "1.0"
arch = "amd64"
maintainer = "Arciris developers <info@dev.arciris.org>"
dependencies = ["libc6 (>= 2.15)", "vim-rt (>= 9.1)"]
description = "ArcirisOS base theme"
license = "MIT"